#### Numpy tutoral - introduction

In [10]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # saving the data in 'list'; It is very similar to list.
print(a, type(a))
b = np.arange(1,9)
print(b, type(b))
'''
Advantage of array over list;
1. Fast 
2. Convinient
3. Less memory
'''


[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>


In [33]:
### Rough comparision of numpy array with python list: In terms of size
import sys
import numpy as np

l = range(1000)
print("Size in terms of list : ",sys.getsizeof(1)*len(l))
#sys.getsizeof(2)

array = np.arange(1000)
print("Size in terms of array : ",array.size*array.itemsize)


Size in terms of list :  28000
Size in terms of array :  8000


In [98]:
### Rough comparision of numpy array with python list: In terms of convinient to use
### numpy is easy to handle/use and faster
import time
import numpy as np

size = 10000000
l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ", (time.time()-start)*1000,"mSec")

# numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000,"mSec")

#Easy addition and subtraction
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1+a2)
print(a1-a2)

python list took:  835.3466987609863 mSec
numpy took:  122.57742881774902 mSec
[5 7 9]
[-3 -3 -3]


[5 7 9]
[-3 -3 -3]


---

In [22]:
#### Python unit testing - Skip/Selectively run tests in pytest.
#### This program won't work in jupyter-notebook
#### Save it in .py format.


import codebasic
import pytest
import sys

#@pytest.mark.skip(reason="I don't want to run this function for the moment")
# The program below the ".skip()" will get skipped.
def test_cal_total():
    total = codebasic.cal_total(6,7)
    assert total == 13

#@pytest.mark.skipif(sys.version_info < (3,5),reason="I don't want to run this function for the moment")    
# If the version of the python is < 3.5, then skip the "test_cal_mul()" 
def test_cal_mul():
    result = codebasic.cal_mul(10,3)
    assert result == 30

'''
To test the specific function in terminal:
$ pytest -k mul      #"mul" or any half name will work. If some part of the name matches it will test that file.
$ pytest -v -rxs     #
'''

'\nTo test the specific function in terminal:\n$ pytest -k mul      #"mul" or any half name will work. If some part of the name matches it will test that file.\n$ pytest -v -rxs     #\n'

#### Python unit testing - skip test, Selectively run tests using their name, Custom markers 

#### [The test code is not running from Jupyter-notebook.](https://www.youtube.com/watch?v=nv9zw454bEk&list=PLeo1K3hjS3uv5U-Lmlnucd7gqF-3ehIh0&index=36)


#### Working with test program

In [ ]:
### The file name and function name in 
### test program must have 'test_' prefix 
### as the file name.

### Python unit testing - pytest introduction.

import codebasic as mathlib

#import practice_program.ipynb as mathlib

def test_cal_total():
    total = mathlib.cal_total(4,5)
    assert total == 9

def test_cal_mul():
    result = mathlib.cal_mul(10,3)
    assert result == 30
   


In [ ]:
#### Program to be tested.

def cal_total(a,b):
    return(a+b)

def cal_mul(a,b):
    return(a*b)

#### Multiprocessing with pool.

In [2]:
### Little intense from the previous one.
### Multiprocessing using pool to use maximum available
### core of the system.

from multiprocessing import Pool
import time

def cal_square(numbers):
    sum = 0
    for i in range(10000):
        sum+=i*i
        
    return sum
if __name__ == "__main__":
    
    p = Pool()
    t1 = time.time()
    sum_result = p.map(cal_square, range(10000))
    p.close()
    p.join()
    
    print("Pool of multiprocess : ", time.time()-t1)
    
    t2 = time.time()
    sum_result2 = []
    for i in range(10000):
        sum_result2.append(cal_square(i))
    
    print("without pool : ", time.time()-t2)

Pool of multiprocess :  2.6074368953704834
without pool :  9.610133647918701


In [12]:
### Simple test Pool program.
from multiprocessing import Pool
import time

def f(n):
    return n*n

if __name__ == "__main__":
    arr = [2, 3, 4, 7]
    p = Pool()
    result = p.map(f, arr)
    print(result)

[4, 9, 16, 49]


#### Function within class:
Working lock in multiprocess with class and function.

In [13]:
import multiprocessing
import time

class with_lock:
    def deposit(balance, lock):
        for i in range(100):
            time.sleep(0.01)
            lock.acquire()
            balance.value +=1
            lock.release()
    
    def withdraw(balance, lock):
        for i in range(100):
            time.sleep(0.01)
            lock.acquire()
            balance.value-=1
            lock.release()

class without_lock:
    def deposit(balance, lock):
        for i in range(100):
            time.sleep(0.01)
            balance.value+=1
            
    def withdraw(balance, lock):
        for i in range(100):
            time.sleep(0.01)
            balance.value-=1
            
    
            
            
if __name__ == "__main__":
    for i in range(5):
        balance = multiprocessing.Value('i', 200)
        lock = multiprocessing.Lock()
        d_lock = multiprocessing.Process(target=with_lock.deposit, args=(balance, lock))
        w_lock = multiprocessing.Process(target=with_lock.withdraw, args=(balance, lock))
        d_lock.start()
        w_lock.start()
        d_lock.join()
        w_lock.join()
        print("Final Balance [with lock] : ", balance.value)
        balance = multiprocessing.Value('i', 200)
        d = multiprocessing.Process(target=without_lock.deposit, args=(balance, lock))
        w = multiprocessing.Process(target=without_lock.withdraw, args=(balance,lock))
        d.start()
        w.start()
        d.join()
        w.join()
        print("Final Balance [without Lock] : ", balance.value)


Final Balance [with lock] :  200
Final Balance [without Lock] :  202
Final Balance [with lock] :  200
Final Balance [without Lock] :  214
Final Balance [with lock] :  200
Final Balance [without Lock] :  206
Final Balance [with lock] :  200
Final Balance [without Lock] :  200
Final Balance [with lock] :  200
Final Balance [without Lock] :  200


#### Lock in multiprocessing

In [119]:
import multiprocessing
import time

def deposit(balance, lock):
    for i in range(10):
        time.sleep(0.01)
        lock.acquire()
        balance.value+=1
        lock.release()
def withdraw(balance, lock):
    for i in range(10):
        time.sleep(0.01)
        lock.acquire()
        balance.value-=1
        lock.release()
if __name__ == "__main__":
    
    balance = multiprocessing.Value('i',200)
    lock = multiprocessing.Lock()
    d = multiprocessing.Process(target=deposit, args=(balance,lock))
    w = multiprocessing.Process(target=withdraw, args=(balance,lock))
    d.start()
    w.start()
    d.join()
    w.join()
    print("Final Balance [With Lock]", balance.value)
        

Final Balance [With Lock] 200


In [32]:
import multiprocessing
import time

def deposit(balance):
   
    for i in range(100):
        time.sleep(0.001)
    
        balance.value+=1
       
        
def widthral(balance):
    
    for i in range(100):
        time.sleep(0.001)
        
        balance.value-=1
        
        
if __name__ == "__main__":
    print("India")
    balance = multiprocessing.Value('i', 200)
    #lock = multiprocessing.Lock()
    q = multiprocessing.Queue()
    p1 = multiprocessing.Process(target=deposit, args=(balance,))
    p2 = multiprocessing.Process(target=widthral, args=(balance,))
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    
    print("Final Balance [Without Lock]:", balance.value)

India
Final Balance [Without Lock]: 202


#### Using queue in multiprocessing

In [20]:
import multiprocessing

def cal_square(numbers, q):
    for n in numbers:
        q.put(n**2)

if __name__ == "__main__":
    arr = [1, 3, 4, 5]
    q = multiprocessing.Queue()
    p1 = multiprocessing.Process(target=cal_square, args=(arr, q))
    p1.start()
    p1.join()
    print('Sharing data between processes using Queue :')
    while not q.empty():
        print(q.get())

Sharing data between processes using Queue :
1
9
16
25


#### Difference between multithreading and multiprocessing

In [51]:
# Multiprocessing generated separate process that can be seen in 
# the task manager where as multithreading don't.

# In multiprocessing, global variable's data also get clear after
# processing of the process unlike multithreading.

import time
import multiprocessing

square_result = []
def cal_square(numbers):
    global square_result
    for n in numbers:
        time.sleep(0.2)
        square_result.append(n**2)
        print("Square : "+str(n**2))
    print("Square_result :", square_result)    
        
if __name__ == "__main__":
    t =  time.time()
    p1 = multiprocessing.Process(target=cal_square, args=(arr,))
    p1.start()
    p1.join()
    
    print("\nResult outside the function : ", square_result)
    
    '''Reason: Every process has its own address space (virtual memory).
     Thus program variables are not shared between two processes.
     You need to use interprocess communication (IPC)
     techniques if you want to share data between two processes.'''

Square : 1
Square : 4
Square : 9
Square : 16
Square_result : [1, 4, 9, 16]

Result outside the function :  []


#### Multiprocessing

In [41]:
#Using multiprocessing using square and cube
#source: codebasic; lecture 27

import time
import multiprocessing

def cal_square(numbers):
    for n in numbers:
        time.sleep(0.2)
        print('Square : '+ str(n**2))
def cal_cube(numbers):
    for n in numbers:
        time.sleep(0.2)
        print('Cube : ' + str(n**3))

if __name__ == '__main__':
    arr = [1, 2, 3, 4]
    t = time.time()
    p1 = multiprocessing.Process(target=cal_square, args=(arr,))
    p2 = multiprocessing.Process(target=cal_square, args=(arr,))
    p1.start()
    p2.start()
    p1.join() #join waits the process of execution till its over.
    p2.join()
    print("Time : ", time.time()-t)

Square : 1
Square : 1
Square : 4Square : 4

Square : 9
Square : 9
Square : 16
Square : 16
Time :  0.8474338054656982


#### [Mutitreading Introduction](https://www.youtube.com/watch?v=PJ4t2U15ACo&list=PLeo1K3hjS3uv5U-Lmlnucd7gqF-3ehIh0&index=29)

In [23]:
### threading and time

In [24]:
import time
import threading

def cal_square(numbers):
    print("Square of a number")
    for n in numbers:
        time.sleep(0.2)
        print("Square :", n**2)
def cal_cube(numbers):
    print("Cube of a number")
    for n in numbers:
        time.sleep(0.2)
        print("Cube :", n**3)

arr = [1, 2, 3, 4]

t = time.time()

t1 = threading.Thread(target=cal_square, args=(arr,))
t2 = threading.Thread(target=cal_cube, args=(arr,))

t1.start()
t2.start()

t1.join()
t2.join()

# cal_square(arr)
# cal_cube(arr)

print("Time taken : ",time.time()-t)

Square of a number
Cube of a number
Square : 1
Cube : 1
Square : 4
Cube : 8
Square : 9
Cube : 27
Square : 16
Cube : 64
Time taken :  0.8050744533538818


---

In [ ]:
import math as m

def res_par(res,cap,freq):
    curr = 100 * 10**-9
    xc = 1/(2*m.pi*freq*cap)
    reac = res*xc/(res+xc)
    vo1 = reac * curr
    vo2 = vo1*10
#    res = (r*(1/2*m.pi*f*c))/(r+(1/2*m.pi*f*c))
    print("For frequency of :",freq," Hz")
    print("\nParalled reactance = ",reac)
    print("\nCapacitive reactance = ",xc)
    print("\nVout of pre-amplifier = ",vo1)
    print("\nVout of second Stage amplifier = ",vo2)
    print("-----------------------------------------------------------\n")

#    return(0)

In [112]:
res_par(res=510000,cap=(100*10**-12),freq=100000) # For frequency of 100kHz
res_par(res=510000,cap=(100*10**-12),freq=10*10**3) # For frequency of 10kHz
res_par(res=510000,cap=(100*10**-12),freq=1*10**3) # For frequency of 1kHz
res_par(res=510000,cap=(100*10**-12),freq=0.1*10**3) # For frequency of 0.1kHz
res_par(res=510000,cap=(100*10**-12),freq=0.01*10**3) # For frequency of 0.01kHz

For frequency of : 100000  Hz

Paralled reactance =  15433.852368902975

Capacitive reactance =  15915.494309189537

Vout of pre-amplifier =  0.0015433852368902977

Vout of second Stage amplifier =  0.015433852368902977
-----------------------------------------------------------

For frequency of : 10000  Hz

Paralled reactance =  121300.7866336865

Capacitive reactance =  159154.94309189534

Vout of pre-amplifier =  0.01213007866336865

Vout of second Stage amplifier =  0.12130078663368651
-----------------------------------------------------------

For frequency of : 1000  Hz

Paralled reactance =  386234.1745698244

Capacitive reactance =  1591549.4309189534

Vout of pre-amplifier =  0.038623417456982445

Vout of second Stage amplifier =  0.38623417456982445
-----------------------------------------------------------

For frequency of : 100.0  Hz

Paralled reactance =  494164.86011903564

Capacitive reactance =  15915494.309189534

Vout of pre-amplifier =  0.04941648601190357

Vout 

ZeroDivisionError: float division by zero